### ISSUE TITLE
wchar_t is 32 bits for Windows targets.

### ISSUE THREAD

**Issue by Demindiro** [Juici/wchar-rs#9]
The `wchar_t` type is 4 bytes wide when building for Windows on Linux platforms. My understanding is that `wchar_t` is supposed to be 16 bits / 2 bytes on Windows platforms, as a simple C program shows:

```
david@pc1:/tmp$ cat size.c 
#include <stddef.h>
#include <stdio.h>

int main() {
	printf("%lu\n", sizeof(wchar_t));
	return 0;
}
david@pc1:/tmp$ gcc size.c -o size && ./size
4
david@pc1:/tmp$ x86_64-w64-mingw32-gcc size.c -o size.exe && wine ./size.exe 
2
```

**Comment by Demindiro** [comment]
Trying to run the tests with `cargo test --target x86_64-pc-windows-gnu` confirms something is wrong as I get this:

```
error[E0308]: mismatched types
 --> tests/wchar_t.rs:4:45
  |
4 | const _: fn(wchar_t) -> libc::wchar_t = |x| x;
  |                                             ^ expected `u16`, found `i32`
  |
```

**Comment by Juici** [comment]
That's interesting, the `wchar_t` in the procedural macro implementation comes from `libc`. It simply uses a trait to determine the type based on the one in the `libc` crate.

There is probably an issue occurring related to the separate build stages of the library. I don't have a Windows machine on hand so I'll need to set up a VM to investigate.

**Comment by Demindiro** [comment]
What I'm guessing is happening is that the macro is built for Linux platforms and hence gets a `ì32` as `wchar_t` type regardless of the target platform of the library/executable being built.
